name: intro to github action

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Intall dependencies
        run: bun install

      - name: build
        run: bun run build

      - name: Run the server
        run: |
          bun run preview &
          sleep 5

      - name: Check if the server is running
        run: curl -I http://localhost:4173
