name: intro to github action

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Intall dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: Run the server
        run: |
          pnpm preview &
          sleep 5

      - name: Check if the server is running
        run: curl -I http://localhost:4173
